// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/airenas/async-api/pkg/clean (interfaces: Cleaner)

package mocks

import (
	pegomock "github.com/petergtz/pegomock"
	"reflect"
	"time"
)

type MockCleaner struct {
	fail func(message string, callerSkip ...int)
}

func NewMockCleaner(options ...pegomock.Option) *MockCleaner {
	mock := &MockCleaner{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockCleaner) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockCleaner) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockCleaner) Clean(_param0 string) error {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockCleaner().")
	}
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("Clean", params, []reflect.Type{reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(error)
		}
	}
	return ret0
}

func (mock *MockCleaner) VerifyWasCalledOnce() *VerifierMockCleaner {
	return &VerifierMockCleaner{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockCleaner) VerifyWasCalled(invocationCountMatcher pegomock.InvocationCountMatcher) *VerifierMockCleaner {
	return &VerifierMockCleaner{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockCleaner) VerifyWasCalledInOrder(invocationCountMatcher pegomock.InvocationCountMatcher, inOrderContext *pegomock.InOrderContext) *VerifierMockCleaner {
	return &VerifierMockCleaner{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockCleaner) VerifyWasCalledEventually(invocationCountMatcher pegomock.InvocationCountMatcher, timeout time.Duration) *VerifierMockCleaner {
	return &VerifierMockCleaner{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockCleaner struct {
	mock                   *MockCleaner
	invocationCountMatcher pegomock.InvocationCountMatcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockCleaner) Clean(_param0 string) *MockCleaner_Clean_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Clean", params, verifier.timeout)
	return &MockCleaner_Clean_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockCleaner_Clean_OngoingVerification struct {
	mock              *MockCleaner
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockCleaner_Clean_OngoingVerification) GetCapturedArguments() string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *MockCleaner_Clean_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
	}
	return
}
